indexing-settings:
  sites:
    - url: https://lenta.ru/
      name: Лента.ру
    - url: https://skillbox.ru/
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru


spring:
  datasource:
    username: root
    password: 12345678Sgt!
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requir
      eSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: false
